-- AlterTable
ALTER TABLE "Bid" ALTER COLUMN "amount" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Listing" ALTER COLUMN "askingPrice" SET DATA TYPE TEXT,
ALTER COLUMN "biddingEnds" SET DATA TYPE TEXT,
ALTER COLUMN "biddingStarts" SET DATA TYPE TEXT,
ALTER COLUMN "reservePrice" SET DATA TYPE TEXT;
